# https://github.com/actions/checkout
# https://github.com/actions/labeler
# https://github.com/crazy-max/ghaction-github-labeler
---
name: configure-repo-labels

on:
  push:
    paths:
      - .github/**/*
    branches:
      - main
  workflow_dispatch: {}

jobs:
  configure-repo-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crazy-max/ghaction-github-labeler@v4.1.0
        if: success()
        with:
          dry-run: false
          github-token: ${{ github.token }}
          skip-delete: false
          yaml-file: .github/labels.yml
